{% set name = "ebolaseq" %}
{% set version = "0.1.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/DaanJansen94/ebolaseq/archive/v{{ version }}.tar.gz
  sha256: eeef92e86638ef23325bedaea9450a15744202bf1b4479d122a5b145fb0882bf

build:
  number: 0
  noarch: python
  entry_points:
    - ebolaseq=ebolaseq.ebolaseq:cli_main
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv"
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - biopython >=1.81
    - numpy >=1.20.0
    - mafft
    - trimal
    - iqtree =2.4.0 #iqtree=2.4.0: more reliable with ebolaseq than v3.0.1
    - minimap2
    - pal2nal
    
test:
  imports:
    - ebolaseq
  commands:
    - ebolaseq --help

about:
  home: https://github.com/DaanJansen94/ebolaseq
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Tool for downloading and analyzing Ebola virus sequences
  description: |
    Ebolaseq is a command-line tool that simplifies the process of analyzing Ebola virus sequences. 
    It automates the complete workflow from downloading sequences to creating phylogenetic trees.
  doc_url: https://github.com/DaanJansen94/ebolaseq/blob/master/README.md
  dev_url: https://github.com/DaanJansen94/ebolaseq

extra:
  recipe-maintainers:
    - DaanJansen94
