{% set name = "ebolaseq" %}
{% set version = "0.1.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/DaanJansen94/ebolaseq/archive/v{{ version }}.tar.gz
  sha256: 096d0dbf1653d4a64e1223e477cb9ec3c2b35d9c7d014f6633be1935bd8d8937

build:
  number: 0
  noarch: python
  entry_points:
    - ebolaseq=ebolaseq.ebolaseq:cli_main
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv"
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:ls
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - conda-forge::mafft        # Force conda-forge for better glibc compatibility
    - bioconda::trimal          # Keep bioconda for specialized tools
    - bioconda::iqtree =2.4.0   # Use Iqtree 2.4.0
    - conda-forge::numpy >=1.20.0    # Force conda-forge for better compatibility
    - conda-forge::biopython >=1.80  # Force conda-forge for better compatibility
    
test:
  imports:
    - ebolaseq
  commands:
    - ebolaseq --help

about:
  home: https://github.com/DaanJansen94/ebolaseq
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Tool for downloading and analyzing Ebola virus sequences
  description: |
    Ebolaseq is a command-line tool that simplifies the process of analyzing Ebola virus sequences. 
    It automates the complete workflow from downloading sequences to creating phylogenetic trees.
  doc_url: https://github.com/DaanJansen94/ebolaseq/blob/master/README.md
  dev_url: https://github.com/DaanJansen94/ebolaseq

extra:
  recipe-maintainers:
    - DaanJansen94
